import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';

import { ReportButton } from '@/components/report-button';
import { SaveButton } from '@/components/save-button';
import { ShareItemCard } from '@/components/share-item-card';
import { TagChips } from '@/components/tag-chips';
import { API_BASE_URL, ApiError, api } from '@/lib/api';
import { formatItemCount, formatRelativeTime } from '@/lib/format';
import { lookupManyRepos, parseGithubUrl } from '@/lib/github';
import { lookupManyOpenAccess } from '@/lib/openalex';
import type { PublicShareResponse } from '@/types/share';

/**
 * The public, no-auth-required collection viewer. THIS IS THE GROWTH LOOP —
 * when someone shares a `https://myetal.app/c/X` link in Slack/Twitter/email,
 * the recipient lands here. Server-rendered for fast first paint, indexed by
 * search engines, and (crucially) crawlable by social-preview bots so the
 * embed shows the collection title + a QR thumbnail.
 *
 * Caching strategy:
 *  - `next.revalidate: 300` on the fetch puts the share in Next's data cache
 *    for 5 minutes; a busy collection survives a Slack-induced thundering herd
 *    without hammering the home server.
 *  - We add a `Cache-Control: public, s-maxage=300, stale-while-revalidate=86400`
 *    header via the layout/page response so any CDN in front of the app
 *    follows the same policy. (Set in `headers()` from the route segment.)
 *  - The QR image is served by the API with its own long max-age.
 */

type PageProps = { params: Promise<{ code: string }> };

const FETCH_OPTIONS = { next: { revalidate: 300 } };

async function fetchPublicShare(
  code: string,
): Promise<{ share: PublicShareResponse | null; gone: boolean }> {
  try {
    const share = await api<PublicShareResponse>(
      `/public/c/${encodeURIComponent(code)}`,
      FETCH_OPTIONS,
    );
    return { share, gone: false };
  } catch (err) {
    if (err instanceof ApiError && err.isNotFound) return { share: null, gone: false };
    if (err instanceof ApiError && err.status === 410) return { share: null, gone: true };
    throw err;
  }
}

// ---------------------------------------------------------------------------
// JSON-LD structured data builder
// ---------------------------------------------------------------------------

interface JsonLdPerson {
  '@type': 'Person';
  name: string;
}

interface JsonLdIdentifier {
  '@type': 'PropertyValue';
  propertyID: string;
  value: string;
}

interface JsonLdArticle {
  '@type': 'ScholarlyArticle';
  headline: string;
  datePublished?: string;
  author?: JsonLdPerson[];
  identifier?: JsonLdIdentifier[];
  url?: string;
}

function parseAuthors(authors: string | null): JsonLdPerson[] | undefined {
  if (!authors) return undefined;
  const names = authors
    .split(',')
    .map((a) => a.trim())
    .filter(Boolean);
  if (names.length === 0) return undefined;
  return names.map((name) => ({ '@type': 'Person' as const, name }));
}

function buildJsonLd(share: PublicShareResponse, siteUrl: string) {
  const hasParts: JsonLdArticle[] = share.items.map((item) => {
    const article: JsonLdArticle = {
      '@type': 'ScholarlyArticle',
      headline: item.title,
    };

    if (item.year) {
      article.datePublished = String(item.year);
    }

    const authors = parseAuthors(item.authors);
    if (authors) {
      article.author = authors;
    }

    if (item.doi) {
      article.identifier = [
        { '@type': 'PropertyValue', propertyID: 'DOI', value: item.doi },
      ];
    }

    if (item.scholar_url) {
      article.url = item.scholar_url;
    }

    return article;
  });

  const ld: Record<string, unknown> = {
    '@context': 'https://schema.org',
    '@type': 'CollectionPage',
    name: share.name,
    url: `${siteUrl}/c/${share.short_code}`,
    dateModified: share.updated_at,
  };

  if (share.description) {
    ld.description = share.description;
  }

  if (share.owner_name) {
    ld.author = { '@type': 'Person', name: share.owner_name };
  }

  if (hasParts.length > 0) {
    ld.hasPart = hasParts;
  }

  return ld;
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { code } = await params;
  const { share, gone } = await fetchPublicShare(code);

  if (!share) {
    return {
      title: gone ? 'Collection removed' : 'Collection not found',
      robots: { index: false },
    };
  }

  const description =
    share.description?.trim() ||
    `${formatItemCount(share.items.length)} shared via MyEtAl`;

  const canonicalPath = `/c/${encodeURIComponent(code)}`;

  return {
    title: share.name,
    description,
    alternates: { canonical: canonicalPath },
    openGraph: {
      title: share.name,
      description,
      type: 'article',
      siteName: 'MyEtAl',
      url: canonicalPath,
      // OG image is auto-generated by the co-located opengraph-image.tsx file
    },
    twitter: {
      card: 'summary_large_image',
      title: share.name,
      description,
      // Twitter image is served by the co-located opengraph-image.tsx file
    },
  };
}

export default async function PublicSharePage({ params }: PageProps) {
  const { code } = await params;
  const { share, gone } = await fetchPublicShare(code);

  if (!share && gone) {
    return (
      <main className="mx-auto flex min-h-screen max-w-2xl flex-col items-center justify-center px-4 py-10 text-center sm:px-6">
        <p className="text-xs uppercase tracking-widest text-ink-faint">410</p>
        <h1 className="mt-4 font-serif text-3xl tracking-tight text-ink sm:text-4xl">
          Collection removed
        </h1>
        <p className="mt-4 max-w-md text-base leading-relaxed text-ink-muted">
          This collection has been taken down. If you believe this was an error,
          please contact the collection owner.
        </p>
        <Link
          href="/"
          className="mt-8 inline-flex min-h-[44px] items-center justify-center rounded-md border border-ink/20 px-5 py-2.5 text-sm font-medium text-ink hover:border-ink/40"
        >
          Back to MyEtAl
        </Link>
      </main>
    );
  }

  if (!share) notFound();

  // Parallel-resolve OpenAlex OA info for every item with a DOI, and GitHub
  // repo info for every repo-kind item. Both lookupMany helpers dedupe and
  // short-circuit on errors so a flaky upstream just hides the augmented row
  // rather than blocking the whole page.
  const [oaByDoi, repoByKey] = await Promise.all([
    lookupManyOpenAccess(share.items.map((i) => i.doi)),
    lookupManyRepos(
      share.items
        .filter((i) => i.kind === 'repo')
        .map((i) => (i.url ? parseGithubUrl(i.url) : null)),
    ),
  ]);

  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://myetal.app';
  const qrUrl = `${API_BASE_URL}/public/c/${encodeURIComponent(code)}/qr.png`;
  const itemCount = share.items.length;

  // Build JSON-LD structured data for search engines.
  // JSON.stringify safely escapes all user-supplied content for embedding.
  const jsonLd = buildJsonLd(share, siteUrl);

  return (
    <main className="mx-auto max-w-2xl px-4 py-8 sm:px-6 sm:py-14">
      {/* eslint-disable-next-line react/no-danger -- JSON.stringify is XSS-safe */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <div className="text-sm text-ink-muted">
        <Link href="/" className="hover:text-ink">
          MyEtAl
        </Link>
      </div>

      <header className="mt-6 sm:mt-8">
        <h1 className="break-words font-serif text-[clamp(1.875rem,7vw,2.25rem)] leading-tight tracking-tight text-ink sm:text-5xl">
          {share.name}
        </h1>
        <div className="mt-3 flex flex-wrap items-center gap-x-3 gap-y-1 text-sm text-ink-muted">
          {share.owner_name ? <span>by {share.owner_name}</span> : null}
          <span aria-hidden>·</span>
          <span>Updated {formatRelativeTime(share.updated_at)}</span>
          <span aria-hidden>·</span>
          <span className="uppercase tracking-wide text-ink-faint">{share.type}</span>
        </div>
        <div className="mt-4">
          <SaveButton
            shortCode={share.short_code}
            name={share.name}
            description={share.description ?? null}
            type={share.type}
            ownerName={share.owner_name ?? null}
            itemCount={share.items.length}
          />
        </div>
        {share.description ? (
          <p className="mt-6 text-base leading-relaxed text-ink">{share.description}</p>
        ) : null}
        {share.tags && share.tags.length > 0 ? (
          <div className="mt-4">
            {/* All tags shown on the detail view; each chip links to the
                /browse list filtered by that tag (PR-B route). */}
            <TagChips
              tags={share.tags}
              max={share.tags.length}
              linkPattern="browse"
            />
          </div>
        ) : null}
      </header>

      <section className="mt-10">
        {itemCount === 0 ? (
          <p className="py-10 text-center text-sm text-ink-muted">
            This collection is empty.
          </p>
        ) : (
          share.items.map((item) => {
            const repoKey =
              item.kind === 'repo' && item.url
                ? (() => {
                    const p = parseGithubUrl(item.url);
                    return p ? `${p.owner}/${p.repo}`.toLowerCase() : null;
                  })()
                : null;
            return (
              <ShareItemCard
                key={item.id}
                item={item}
                oa={item.doi ? oaByDoi.get(item.doi.trim()) ?? null : null}
                repo={repoKey ? repoByKey.get(repoKey) ?? null : null}
              />
            );
          })
        )}
      </section>

      {share.related_shares?.length > 0 ? (
        <section className="mt-16 border-t border-rule pt-8">
          <h2 className="font-serif text-lg text-ink">Who else shares these papers</h2>
          <p className="mt-1 text-sm text-ink-muted">
            Other public collections with papers in common.
          </p>
          <ul className="mt-4 space-y-2">
            {share.related_shares.map((rs) => (
              <li key={rs.short_code}>
                <Link
                  href={`/c/${rs.short_code}`}
                  className="group flex items-center justify-between rounded-md px-3 py-2.5 transition-colors hover:bg-surface-sunken"
                >
                  <span className="text-sm font-medium text-ink group-hover:underline">
                    {rs.name}
                  </span>
                  <span className="ml-3 shrink-0 rounded-full bg-surface-sunken px-2 py-0.5 text-xs tabular-nums text-ink-muted group-hover:bg-white">
                    {rs.papers_in_common} in common
                  </span>
                </Link>
              </li>
            ))}
          </ul>
        </section>
      ) : null}

      {share.similar_shares?.length > 0 ? (
        <section className="mt-10 border-t border-rule pt-8">
          <h2 className="font-serif text-lg text-ink">Similar collections</h2>
          <p className="mt-1 text-sm text-ink-muted">
            Collections with the most overlap in papers.
          </p>
          <ul className="mt-4 space-y-2">
            {share.similar_shares.map((ss) => (
              <li key={ss.short_code}>
                <Link
                  href={`/c/${ss.short_code}`}
                  className="group flex items-center justify-between rounded-md px-3 py-2.5 transition-colors hover:bg-surface-sunken"
                >
                  <span className="text-sm font-medium text-ink group-hover:underline">
                    {ss.name}
                  </span>
                  <span className="ml-3 shrink-0 rounded-full bg-surface-sunken px-2 py-0.5 text-xs tabular-nums text-ink-muted group-hover:bg-white">
                    {ss.papers_in_common} in common
                  </span>
                </Link>
              </li>
            ))}
          </ul>
        </section>
      ) : null}

      <aside className="mt-16 border-t border-rule pt-8">
        <div className="flex flex-col items-center gap-5 text-center sm:flex-row sm:items-center sm:justify-between sm:gap-6 sm:text-left">
          <div>
            <p className="font-serif text-lg text-ink">Scan to keep this</p>
            <p className="mt-1 text-sm text-ink-muted">
              {formatItemCount(itemCount)} ·{' '}
              <code className="text-ink">/c/{share.short_code}</code>
            </p>
          </div>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={qrUrl}
            alt={`QR code for "${share.name}"`}
            width={160}
            height={160}
            className="h-40 w-40 rounded-md border border-rule bg-white p-2 sm:h-36 sm:w-36"
          />
        </div>
      </aside>

      <footer className="mt-16 space-y-4 border-t border-rule pt-8">
        <ReportButton shortCode={share.short_code} />
        <p className="text-xs text-ink-faint">
          Built with MyEtAl ·{' '}
          <Link href="/" className="underline-offset-2 hover:underline">
            myetal.app
          </Link>
          {' · '}
          <Link href="/dashboard/search" className="underline-offset-2 hover:underline">
            Search collections
          </Link>
          {' · '}
          <Link href="/privacy" className="underline-offset-2 hover:underline">
            Privacy
          </Link>
          {' · '}
          <Link href="/terms" className="underline-offset-2 hover:underline">
            Terms
          </Link>
        </p>
      </footer>
    </main>
  );
}
